In [1]:
import pandas as pd
df1 = pd.read_csv('hospital_pharmacy(23.03)/1.병원정보서비스.csv')

In [2]:
df1['종별코드']=28 #요양병원

In [3]:
df1 #76603 rows × 30 columns

,암호화요양기호,요양기관명,종별코드,종별코드명,시도코드,시도코드명,시군구코드,시군구코드명,읍면동,우편번호,...,치과인턴 인원수,치과레지던트 인원수,치과전문의 인원수,한방일반의 인원수,한방인턴 인원수,한방레지던트 인원수,한방전문의 인원수,조산사 인원수,좌표(X),좌표(Y)
0,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,상급종합,220000,인천,220003,인천부평구,부평동,21431,...,0,0,2,0,0,0,0,0,126.724899,37.484831
1,JDQ4MTYyMiM1MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIy...,강릉아산병원,28,상급종합,320000,강원,320100,강릉시,NaN,25440,...,0,0,2,0,0,0,0,0,128.857841,37.818433
2,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,강북삼성병원,28,상급종합,110000,서울,110016,종로구,NaN,3181,...,0,0,4,0,0,0,0,0,126.967750,37.568408
3,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,건국대학교병원,28,상급종합,110000,서울,110023,광진구,NaN,5030,...,0,0,3,0,0,0,0,0,127.071828,37.540376
4,JDQ4MTYyMiM4MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,경북대학교병원,28,상급종합,230000,대구,230006,대구중구,NaN,41944,...,0,0,1,0,0,0,0,0,128.604703,35.866253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76598,JDU4MTI3MSM1MSMkMSMkMCMkMTMkNDgxOTYxIzExIyQxIy...,힘나는한의원,28,한의원,310000,경기,312300,김포시,NaN,10099,...,0,0,0,1,0,0,0,0,126.704889,37.632495
76599,JDQ4MTg4MSM1MSMkMSMkNCMkMTMkNDgxOTYxIzUxIyQxIy...,힘내라한의원,28,한의원,110000,서울,110003,강서구,NaN,7526,...,0,0,0,2,0,0,0,0,126.855061,37.561526
76600,JDQ4MTg4MSM1MSMkMSMkNCMkMTMkNDgxMzUxIzUxIyQxIy...,힘찬마디한의원,28,한의원,110000,서울,110002,강동구,천호동,5329,...,0,0,0,1,0,0,0,0,127.126346,37.538174
76601,JDQ4MTg4MSM1MSMkMSMkNCMkMTMkMzgxNzAyIzUxIyQxIy...,힘찬세상경희한의원,28,한의원,110000,서울,110014,용산구,한강로2가,4376,...,0,0,0,0,0,0,1,0,126.968167,37.530005
76602,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,한의원,380000,경남,380500,진주시,NaN,52697,...,0,0,0,1,0,0,0,0,128.064558,35.178636

In [5]:
df1.info() #읍면동, 전화번호, 병원홈페이지, 개설일자, 좌표(x,y)에서 결측치 있음. 
#위치 없는곳이 제거 해도 될 곳 1순위라고 생각. 좌표 결측치 있는 병원 제거

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76603 entries, 0 to 76602
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   암호화요양기호     76603 non-null  object
 1   요양기관명       76603 non-null  object
 2   종별코드        76603 non-null  int64
 3   종별코드명       76603 non-null  object
 4   시도코드        76603 non-null  int64
 5   시도코드명       76603 non-null  object
 6   시군구코드       76603 non-null  int64
 7   시군구코드명      76603 non-null  object
 8   읍면동         26627 non-null  object
 9   우편번호        76603 non-null  int64
 10  주소          76603 non-null  object
 11  전화번호        76233 non-null  object
 12  병원홈페이지      8842 non-null   object
 13  개설일자        76599 non-null  float64
 14  총의사수        76603 non-null  int64
 15  의과일반의 인원수   76603 non-null  int64
 16  의과인턴 인원수    76603 non-null  int64
 17  의과레지던트 인원수  76603 non-null  int64
 18  의과전문의 인원수   76603 non-null  int64
 19  치과일반의 인원수   76603 non-null  int64
 20  치과인턴 인원수    76603 non-null  int64
 21  치과레지던트 인원수  76603 non-null  int64
 22  치과전문의 인원수   76603 non-null  int64
 23  한방일반의 인원수   76603 non-null  int64
 24  한방인턴 인원수    76603 non-null  int64
 25  한방레지던트 인원수  76603 non-null  int64
 26  한방전문의 인원수   76603 non-null  int64
 27  조산사 인원수     76603 non-null  int64
 28  좌표(X)       76525 non-null  float64
 29  좌표(Y)       76525 non-null  float64
dtypes: float64(3), int64(18), object(9)
memory usage: 17.5+ MB

In [6]:
df5 = pd.read_csv('hospital_pharmacy(23.03)/5.의료기관별상세정보서비스_03_진료과목정보.csv')
df5['종별코드']=28

In [7]:
df5 #370866 rows × 7 columns

,암호화요양기호,요양기관명,진료과목코드,진료과목코드명,과목별 전문의수,선택진료 의사수,종별코드
0,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교 여의도성모병원,1,내과,36,0,28
1,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,경희대학교병원,1,내과,64,0,28
2,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,순천향대학교 부속 서울병원,1,내과,60,0,28
3,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,인제대학교 서울백병원,1,내과,13,0,28
4,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교 은평성모병원,1,내과,50,0,28
...,...,...,...,...,...,...,...
370861,JDQ4MTg4MSM1MSMkMSMkMCMkMTMkMzgxNzAyIzUxIyQxIy...,진성한의원,88,한방응급,0,0,28
370862,JDQ4MTg4MSM1MSMkMSMkMCMkMTMkMzgxNzAyIzUxIyQxIy...,엄한의원,88,한방응급,0,0,28
370863,JDQ4MTg4MSM1MSMkMSMkMCMkMTMkMzgxNzAyIzUxIyQyIy...,이상용한의원,88,한방응급,0,0,28
370864,JDQ4MTg4MSM1MSMkMSMkMCMkMTMkNDgxMzUxIzExIyQxIy...,인수당한의원,88,한방응급,0,0,28
370865,JDQ4MTg4MSM1MSMkMSMkMCMkMTMkMzgxNzAyIzUxIyQyIy...,연세한의원,88,한방응급,0,0,28

In [8]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370866 entries, 0 to 370865
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   암호화요양기호   370866 non-null  object
 1   요양기관명     370866 non-null  object
 2   진료과목코드    370866 non-null  int64
 3   진료과목코드명   370866 non-null  object
 4   과목별 전문의수  370866 non-null  int64
 5   선택진료 의사수  370866 non-null  int64
 6   종별코드      370866 non-null  int64
dtypes: int64(4), object(3)
memory usage: 19.8+ MB

In [14]:
df5['진료과목코드명'].value_counts().head(10)

내과              23635
피부과             16909
한방내과            16549
소아청소년과          15630
침구과             14900
한방부인과           14535
한방소아과           14274
한방안·이비인후·피부과    13994
한방신경정신과         13484
한방재활의학과         12792
Name: 진료과목코드명, dtype: int64

In [37]:
df = pd.merge(left=df1, # 왼쪽 DataFrame 지정
              right=df5, # 오른쪽 DataFrame 지정
              how='left', # 조인 방법 지정
              left_on='암호화요양기호', # 왼쪽 DataFrame에서 기준으로 삼을 열 지정
              right_on='암호화요양기호')

In [38]:
df #373914 rows × 36 columns

,암호화요양기호,요양기관명_x,종별코드_x,종별코드명,시도코드,시도코드명,시군구코드,시군구코드명,읍면동,우편번호,...,한방전문의 인원수,조산사 인원수,좌표(X),좌표(Y),요양기관명_y,진료과목코드,진료과목코드명,과목별 전문의수,선택진료 의사수,종별코드_y
0,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,1.0,내과,60.0,0.0,28.0
1,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,2.0,신경과,6.0,0.0,28.0
2,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,3.0,정신건강의학과,4.0,0.0,28.0
3,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,4.0,외과,25.0,0.0,28.0
4,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,5.0,정형외과,9.0,0.0,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373909,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,83.0,한방안·이비인후·피부과,0.0,0.0,28.0
373910,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,84.0,한방신경정신과,0.0,0.0,28.0
373911,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,85.0,침구과,0.0,0.0,28.0
373912,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,86.0,한방재활의학과,0.0,0.0,28.0
373913,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,87.0,사상체질과,0.0,0.0,28.0

In [48]:
df['진료과목코드'].isna().sum()

3048

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 373914 entries, 0 to 373913
Data columns (total 36 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   암호화요양기호     373914 non-null  object
 1   요양기관명_x     373914 non-null  object
 2   종별코드_x      373914 non-null  int64
 3   종별코드명       373914 non-null  object
 4   시도코드        373914 non-null  int64
 5   시도코드명       373914 non-null  object
 6   시군구코드       373914 non-null  int64
 7   시군구코드명      373914 non-null  object
 8   읍면동         92846 non-null   object
 9   우편번호        373914 non-null  int64
 10  주소          373914 non-null  object
 11  전화번호        372028 non-null  object
 12  병원홈페이지      43630 non-null   object
 13  개설일자        373910 non-null  float64
 14  총의사수        373914 non-null  int64
 15  의과일반의 인원수   373914 non-null  int64
 16  의과인턴 인원수    373914 non-null  int64
 17  의과레지던트 인원수  373914 non-null  int64
 18  의과전문의 인원수   373914 non-null  int64
 19  치과일반의 인원수   373914 non-null  int64
 20  치과인턴 인원수    373914 non-null  int64
 21  치과레지던트 인원수  373914 non-null  int64
 22  치과전문의 인원수   373914 non-null  int64
 23  한방일반의 인원수   373914 non-null  int64
 24  한방인턴 인원수    373914 non-null  int64
 25  한방레지던트 인원수  373914 non-null  int64
 26  한방전문의 인원수   373914 non-null  int64
 27  조산사 인원수     373914 non-null  int64
 28  좌표(X)       373583 non-null  float64
 29  좌표(Y)       373583 non-null  float64
 30  요양기관명_y     370866 non-null  object
 31  진료과목코드      370866 non-null  float64
 32  진료과목코드명     370866 non-null  object
 33  과목별 전문의수    370866 non-null  float64
 34  선택진료 의사수    370866 non-null  float64
 35  종별코드_y      370866 non-null  float64
dtypes: float64(7), int64(18), object(11)
memory usage: 105.6+ MB

In [118]:
df_code = df.dropna(subset=['진료과목코드']) #진료과목코드 없는 병원 삭제

In [104]:
df_code

,암호화요양기호,요양기관명_x,종별코드_x,종별코드명,시도코드,시도코드명,시군구코드,시군구코드명,읍면동,우편번호,...,한방전문의 인원수,조산사 인원수,좌표(X),좌표(Y),요양기관명_y,진료과목코드,진료과목코드명,과목별 전문의수,선택진료 의사수,종별코드_y
0,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,1.0,내과,60.0,0.0,28.0
1,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,2.0,신경과,6.0,0.0,28.0
2,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,3.0,정신건강의학과,4.0,0.0,28.0
3,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,4.0,외과,25.0,0.0,28.0
4,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,부평동,21431,...,0,0,126.724899,37.484831,가톨릭대학교인천성모병원,5.0,정형외과,9.0,0.0,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373909,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,83.0,한방안·이비인후·피부과,0.0,0.0,28.0
373910,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,84.0,한방신경정신과,0.0,0.0,28.0
373911,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,85.0,침구과,0.0,0.0,28.0
373912,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,86.0,한방재활의학과,0.0,0.0,28.0
373913,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,NaN,52697,...,0,0,128.064558,35.178636,힘찬한의원,87.0,사상체질과,0.0,0.0,28.0

In [119]:
df_code.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 370866 entries, 0 to 373913
Data columns (total 33 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   암호화요양기호     370866 non-null  object
 1   요양기관명       370866 non-null  object
 2   종별코드        370866 non-null  int64
 3   종별코드명       370866 non-null  object
 4   시도코드        370866 non-null  int64
 5   시도코드명       370866 non-null  object
 6   시군구코드       370866 non-null  int64
 7   시군구코드명      370866 non-null  object
 8   우편번호        370866 non-null  int64
 9   주소          370866 non-null  object
 10  전화번호        368981 non-null  object
 11  병원홈페이지      43459 non-null   object
 12  개설일자        370865 non-null  float64
 13  총의사수        370866 non-null  int64
 14  의과일반의 인원수   370866 non-null  int64
 15  의과인턴 인원수    370866 non-null  int64
 16  의과레지던트 인원수  370866 non-null  int64
 17  의과전문의 인원수   370866 non-null  int64
 18  치과일반의 인원수   370866 non-null  int64
 19  치과인턴 인원수    370866 non-null  int64
 20  치과레지던트 인원수  370866 non-null  int64
 21  치과전문의 인원수   370866 non-null  int64
 22  한방일반의 인원수   370866 non-null  int64
 23  한방인턴 인원수    370866 non-null  int64
 24  한방레지던트 인원수  370866 non-null  int64
 25  한방전문의 인원수   370866 non-null  int64
 26  조산사 인원수     370866 non-null  int64
 27  좌표(X)       370535 non-null  float64
 28  좌표(Y)       370535 non-null  float64
 29  진료과목코드      370866 non-null  float64
 30  진료과목코드명     370866 non-null  object
 31  과목별 전문의수    370866 non-null  float64
 32  선택진료 의사수    370866 non-null  float64
dtypes: float64(6), int64(18), object(9)
memory usage: 96.2+ MB

In [105]:
df_code=df_code.drop(['요양기관명_y', '종별코드_y','읍면동'], axis=1) #중복 열, 불필요햔 열 제거

In [111]:
df_code=df_code.rename(columns={'요양기관명_x':'요양기관명'})

In [115]:
df_code=df_code.rename(columns={'종별코드_x':'종별코드'})

In [120]:
df_code.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 370866 entries, 0 to 373913
Data columns (total 33 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   암호화요양기호     370866 non-null  object
 1   요양기관명       370866 non-null  object
 2   종별코드        370866 non-null  int64
 3   종별코드명       370866 non-null  object
 4   시도코드        370866 non-null  int64
 5   시도코드명       370866 non-null  object
 6   시군구코드       370866 non-null  int64
 7   시군구코드명      370866 non-null  object
 8   우편번호        370866 non-null  int64
 9   주소          370866 non-null  object
 10  전화번호        368981 non-null  object
 11  병원홈페이지      43459 non-null   object
 12  개설일자        370865 non-null  float64
 13  총의사수        370866 non-null  int64
 14  의과일반의 인원수   370866 non-null  int64
 15  의과인턴 인원수    370866 non-null  int64
 16  의과레지던트 인원수  370866 non-null  int64
 17  의과전문의 인원수   370866 non-null  int64
 18  치과일반의 인원수   370866 non-null  int64
 19  치과인턴 인원수    370866 non-null  int64
 20  치과레지던트 인원수  370866 non-null  int64
 21  치과전문의 인원수   370866 non-null  int64
 22  한방일반의 인원수   370866 non-null  int64
 23  한방인턴 인원수    370866 non-null  int64
 24  한방레지던트 인원수  370866 non-null  int64
 25  한방전문의 인원수   370866 non-null  int64
 26  조산사 인원수     370866 non-null  int64
 27  좌표(X)       370535 non-null  float64
 28  좌표(Y)       370535 non-null  float64
 29  진료과목코드      370866 non-null  float64
 30  진료과목코드명     370866 non-null  object
 31  과목별 전문의수    370866 non-null  float64
 32  선택진료 의사수    370866 non-null  float64
dtypes: float64(6), int64(18), object(9)
memory usage: 96.2+ MB

In [126]:
#좌표없는 병원 제거
df_code = df_code.dropna(subset=['좌표(X)']) #370535개의 열로 줄임.

In [127]:
df_code.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 370535 entries, 0 to 373913
Data columns (total 33 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   암호화요양기호     370535 non-null  object
 1   요양기관명       370535 non-null  object
 2   종별코드        370535 non-null  int64
 3   종별코드명       370535 non-null  object
 4   시도코드        370535 non-null  int64
 5   시도코드명       370535 non-null  object
 6   시군구코드       370535 non-null  int64
 7   시군구코드명      370535 non-null  object
 8   우편번호        370535 non-null  int64
 9   주소          370535 non-null  object
 10  전화번호        368660 non-null  object
 11  병원홈페이지      43459 non-null   object
 12  개설일자        370535 non-null  float64
 13  총의사수        370535 non-null  int64
 14  의과일반의 인원수   370535 non-null  int64
 15  의과인턴 인원수    370535 non-null  int64
 16  의과레지던트 인원수  370535 non-null  int64
 17  의과전문의 인원수   370535 non-null  int64
 18  치과일반의 인원수   370535 non-null  int64
 19  치과인턴 인원수    370535 non-null  int64
 20  치과레지던트 인원수  370535 non-null  int64
 21  치과전문의 인원수   370535 non-null  int64
 22  한방일반의 인원수   370535 non-null  int64
 23  한방인턴 인원수    370535 non-null  int64
 24  한방레지던트 인원수  370535 non-null  int64
 25  한방전문의 인원수   370535 non-null  int64
 26  조산사 인원수     370535 non-null  int64
 27  좌표(X)       370535 non-null  float64
 28  좌표(Y)       370535 non-null  float64
 29  진료과목코드      370535 non-null  float64
 30  진료과목코드명     370535 non-null  object
 31  과목별 전문의수    370535 non-null  float64
 32  선택진료 의사수    370535 non-null  float64
dtypes: float64(6), int64(18), object(9)
memory usage: 96.1+ MB

## 병원별 진료과목 추출하기

In [128]:
df_code

,암호화요양기호,요양기관명,종별코드,종별코드명,시도코드,시도코드명,시군구코드,시군구코드명,우편번호,주소,...,한방인턴 인원수,한방레지던트 인원수,한방전문의 인원수,조산사 인원수,좌표(X),좌표(Y),진료과목코드,진료과목코드명,과목별 전문의수,선택진료 의사수
0,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,21431,인천광역시 부평구 동수로 56 (부평동),...,0,0,0,0,126.724899,37.484831,1.0,내과,60.0,0.0
1,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,21431,인천광역시 부평구 동수로 56 (부평동),...,0,0,0,0,126.724899,37.484831,2.0,신경과,6.0,0.0
2,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,21431,인천광역시 부평구 동수로 56 (부평동),...,0,0,0,0,126.724899,37.484831,3.0,정신건강의학과,4.0,0.0
3,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,21431,인천광역시 부평구 동수로 56 (부평동),...,0,0,0,0,126.724899,37.484831,4.0,외과,25.0,0.0
4,JDQ4MTYyMiM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,가톨릭대학교인천성모병원,28,요양병원,220000,인천,220003,인천부평구,21431,인천광역시 부평구 동수로 56 (부평동),...,0,0,0,0,126.724899,37.484831,5.0,정형외과,9.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373909,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,52697,경상남도 진주시 진양호로 284 2층 (신안동),...,0,0,0,0,128.064558,35.178636,83.0,한방안·이비인후·피부과,0.0,0.0
373910,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,52697,경상남도 진주시 진양호로 284 2층 (신안동),...,0,0,0,0,128.064558,35.178636,84.0,한방신경정신과,0.0,0.0
373911,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,52697,경상남도 진주시 진양호로 284 2층 (신안동),...,0,0,0,0,128.064558,35.178636,85.0,침구과,0.0,0.0
373912,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,52697,경상남도 진주시 진양호로 284 2층 (신안동),...,0,0,0,0,128.064558,35.178636,86.0,한방재활의학과,0.0,0.0
373913,JDQ4MTYyMiM4MSMkMSMkNCMkMTMkNDgxMzUxIzMxIyQxIy...,힘찬한의원,28,요양병원,380000,경남,380500,진주시,52697,경상남도 진주시 진양호로 284 2층 (신안동),...,0,0,0,0,128.064558,35.178636,87.0,사상체질과,0.0,0.0

In [132]:
df_code.loc[:,['요양기관명','진료과목코드명']]

               요양기관명       진료과목코드명
0       가톨릭대학교인천성모병원            내과
1       가톨릭대학교인천성모병원           신경과
2       가톨릭대학교인천성모병원       정신건강의학과
3       가톨릭대학교인천성모병원            외과
4       가톨릭대학교인천성모병원          정형외과
...              ...           ...
373909         힘찬한의원  한방안·이비인후·피부과
373910         힘찬한의원       한방신경정신과
373911         힘찬한의원           침구과
373912         힘찬한의원       한방재활의학과
373913         힘찬한의원         사상체질과

[370535 rows x 2 columns]

In [ ]:
직방, 다방처럼 사용자가 원하는 조건을 입력하면 병원을 추천해주는 시스템
비용, 병상수, 전문의