# [아이템 기반 최근접 이웃 협업 필터링]
## 데이터 전처리
1. 병원데이터에서 필요한부분만 가져오기  
- 필요없는 column제거
- 병원 id 재부여
2. 사용자별 병원 10곳 추출 후 임의로 평점 매기기

### 1. 병원데이터에서 필요한부분만 가져오기

In [5]:
import pandas as pd
meta = pd.read_csv('전국요양병원api.csv')

In [6]:
meta #1364 rows × 13 columns

,id,name,location,phonenumber,category,photo,open_time,credit,createdat,updatedat,province,xpos,ypos
0,1,행복한요양병원,경기도 안산시 단원구 고잔동 704-2 201호,NaN,NaN,NaN,NaN,0,2023-05-12 23:12,2023-05-12 23:12,경기,126.827683,37.313547
1,2,해오름요양병원,경기도 안산시 단원구 선부동 1034번지 8호,NaN,"침구과, 한방신경정신과, 한방안·이비인후·피부과, 한방내과, 비뇨기과, 정형외과, ...",NaN,NaN,0,2023-05-12 23:12,2023-05-12 23:12,경기,126.807603,37.342222
2,3,세명요양병원,경기도 안산시 상록구 본오1동 904번지 13호 외 1필지,NaN,"침구과, 사상체질과, 한방재활의학과, 한방신경정신과, 한방안·이비인후·피부과, 한방...",NaN,NaN,0,2023-05-12 23:12,2023-05-12 23:12,경기,126.862995,37.290667
3,4,양주큰길요양병원,경기도 양주시 광적면 가납리 495-2번지,NaN,"내과, 신경과, 외과, 정형외과, 신경외과, 산부인과, 재활의학과, 가정의학과, 한방내과",NaN,NaN,0,2023-05-12 23:12,2023-05-12 23:12,경기,126.995532,37.810187
4,5,중앙효요양병원,경기도 의정부시 의정부동 237번지 7호,NaN,"외과, 침구과",NaN,NaN,0,2023-05-12 23:12,2023-05-12 23:12,경기,127.045456,37.746234
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1359,7411,의료법인홍익의료재단파스카요양병원,"충청북도 청주시 청원구 내수읍 마산길 8-11, ()",043-900-1004,가정의학과,NaN,NaN,0,2023-05-12 23:13,2023-05-12 23:13,충북,127.538810,36.717401
1360,7420,이가양정요양병원,"광주광역시 광산구 하남울로 10, (하남동)",062-675-7777,가정의학과,NaN,NaN,0,2023-05-12 23:13,2023-05-12 23:13,광주,126.802241,35.181146
1361,7567,평심요양병원,"경상남도 양산시 하북면 신평로 37, 2~6층",055-800-7090,가정의학과,NaN,NaN,0,2023-05-12 23:13,2023-05-12 23:13,경남,129.086478,35.491624
1362,7637,현송요양병원,"전라남도 여수시 해산4길 37-0, (해산동)",061-691-1000,가정의학과,NaN,NaN,0,2023-05-12 23:13,2023-05-12 23:13,전남,127.633647,34.802020
1363,7640,혜민요양병원,"강원도 평창군 봉평면 북길동길 17,",033-336-0216,가정의학과,NaN,NaN,0,2023-05-12 23:13,2023-05-12 23:13,강원,128.376613,37.623099

In [7]:
meta.value_counts(meta['open_time'])

Series([], dtype: int64)

In [8]:
type(meta)

pandas.core.frame.DataFrame

In [9]:
meta1 = meta.drop(['photo','open_time','credit','createdat','updatedat'],axis=1)

In [10]:
meta1

,id,name,location,phonenumber,category,province,xpos,ypos
0,1,행복한요양병원,경기도 안산시 단원구 고잔동 704-2 201호,NaN,NaN,경기,126.827683,37.313547
1,2,해오름요양병원,경기도 안산시 단원구 선부동 1034번지 8호,NaN,"침구과, 한방신경정신과, 한방안·이비인후·피부과, 한방내과, 비뇨기과, 정형외과, ...",경기,126.807603,37.342222
2,3,세명요양병원,경기도 안산시 상록구 본오1동 904번지 13호 외 1필지,NaN,"침구과, 사상체질과, 한방재활의학과, 한방신경정신과, 한방안·이비인후·피부과, 한방...",경기,126.862995,37.290667
3,4,양주큰길요양병원,경기도 양주시 광적면 가납리 495-2번지,NaN,"내과, 신경과, 외과, 정형외과, 신경외과, 산부인과, 재활의학과, 가정의학과, 한방내과",경기,126.995532,37.810187
4,5,중앙효요양병원,경기도 의정부시 의정부동 237번지 7호,NaN,"외과, 침구과",경기,127.045456,37.746234
...,...,...,...,...,...,...,...,...
1359,7411,의료법인홍익의료재단파스카요양병원,"충청북도 청주시 청원구 내수읍 마산길 8-11, ()",043-900-1004,가정의학과,충북,127.538810,36.717401
1360,7420,이가양정요양병원,"광주광역시 광산구 하남울로 10, (하남동)",062-675-7777,가정의학과,광주,126.802241,35.181146
1361,7567,평심요양병원,"경상남도 양산시 하북면 신평로 37, 2~6층",055-800-7090,가정의학과,경남,129.086478,35.491624
1362,7637,현송요양병원,"전라남도 여수시 해산4길 37-0, (해산동)",061-691-1000,가정의학과,전남,127.633647,34.802020
1363,7640,혜민요양병원,"강원도 평창군 봉평면 북길동길 17,",033-336-0216,가정의학과,강원,128.376613,37.623099

In [11]:
type(meta1['category'])

pandas.core.series.Series

In [12]:
list = meta1['category']

In [13]:
list

0                                                     NaN
1       침구과, 한방신경정신과, 한방안·이비인후·피부과, 한방내과, 비뇨기과, 정형외과, ...
2       침구과, 사상체질과, 한방재활의학과, 한방신경정신과, 한방안·이비인후·피부과, 한방...
3       내과, 신경과, 외과, 정형외과, 신경외과, 산부인과, 재활의학과, 가정의학과, 한방내과
4                                                 외과, 침구과
                              ...
1359                                                가정의학과
1360                                                가정의학과
1361                                                가정의학과
1362                                                가정의학과
1363                                                가정의학과
Name: category, Length: 1364, dtype: object

In [14]:
sum(list.isna())

1

In [15]:
meta1['id']

0          1
1          2
2          3
3          4
4          5
        ...
1359    7411
1360    7420
1361    7567
1362    7637
1363    7640
Name: id, Length: 1364, dtype: int64

In [16]:
sum(meta1.duplicated(subset=['id'], keep=False))#id에는 중복값 없음.

0

In [17]:
meta1['id'] = [i+1 for i in range(len(meta['id']))]

In [18]:
meta1 #병원별 id ->  rename

,id,name,location,phonenumber,category,province,xpos,ypos
0,1,행복한요양병원,경기도 안산시 단원구 고잔동 704-2 201호,NaN,NaN,경기,126.827683,37.313547
1,2,해오름요양병원,경기도 안산시 단원구 선부동 1034번지 8호,NaN,"침구과, 한방신경정신과, 한방안·이비인후·피부과, 한방내과, 비뇨기과, 정형외과, ...",경기,126.807603,37.342222
2,3,세명요양병원,경기도 안산시 상록구 본오1동 904번지 13호 외 1필지,NaN,"침구과, 사상체질과, 한방재활의학과, 한방신경정신과, 한방안·이비인후·피부과, 한방...",경기,126.862995,37.290667
3,4,양주큰길요양병원,경기도 양주시 광적면 가납리 495-2번지,NaN,"내과, 신경과, 외과, 정형외과, 신경외과, 산부인과, 재활의학과, 가정의학과, 한방내과",경기,126.995532,37.810187
4,5,중앙효요양병원,경기도 의정부시 의정부동 237번지 7호,NaN,"외과, 침구과",경기,127.045456,37.746234
...,...,...,...,...,...,...,...,...
1359,1360,의료법인홍익의료재단파스카요양병원,"충청북도 청주시 청원구 내수읍 마산길 8-11, ()",043-900-1004,가정의학과,충북,127.538810,36.717401
1360,1361,이가양정요양병원,"광주광역시 광산구 하남울로 10, (하남동)",062-675-7777,가정의학과,광주,126.802241,35.181146
1361,1362,평심요양병원,"경상남도 양산시 하북면 신평로 37, 2~6층",055-800-7090,가정의학과,경남,129.086478,35.491624
1362,1363,현송요양병원,"전라남도 여수시 해산4길 37-0, (해산동)",061-691-1000,가정의학과,전남,127.633647,34.802020
1363,1364,혜민요양병원,"강원도 평창군 봉평면 북길동길 17,",033-336-0216,가정의학과,강원,128.376613,37.623099

In [19]:
# csv 파일로 저장
df.to_csv('hospital.csv', index=False)

### 2. 사용자별 병원 평점 파일 생성

In [52]:
import numpy as np
import pandas as pd

# 600명의 사용자 id 생성
user_ids = np.arange(1, 601)

# 1364개의 병원 id 생성
hospital_ids = np.arange(1, 1365)

# 각 사용자별로 랜덤하게 10개의 병원 선택
selected_hospitals = np.random.choice(hospital_ids, size=(600, 10), replace=True) #복원추출

# 선택된 10개의 병원에 대해 1~5사이의 랜덤한 평점 부여
ratings = np.random.randint(1, 6, size=(600, 10))

# 데이터프레임 생성
df = pd.DataFrame(data=np.column_stack((np.repeat(user_ids, 10), selected_hospitals.ravel(), ratings.ravel())),
                  columns=['user_id', 'id', 'rating'])
df

      user_id    id  rating
0           1   811       2
1           1   908       4
2           1  1305       5
3           1   116       3
4           1   765       1
...       ...   ...     ...
5995      600   730       5
5996      600   402       5
5997      600   888       2
5998      600   888       5
5999      600   703       2

[6000 rows x 3 columns]

In [53]:
# csv 파일로 저장
df.to_csv('ratings.csv', index=False)

In [54]:
df.describe()

           user_id           id       rating
count  6000.000000  6000.000000  6000.000000
mean    300.500000   691.801667     2.990000
std     173.219276   396.540810     1.412999
min       1.000000     1.000000     1.000000
25%     150.750000   348.000000     2.000000
50%     300.500000   695.000000     3.000000
75%     450.250000  1044.250000     4.000000
max     600.000000  1364.000000     5.000000

## 아이템 기반 최근접 이웃 협업 필터링
* 사용자 기반 : 각 사용자와 비슷한 고객들의 행동 참고
* 아이템 기반 : 해당 아이템을 선택한 다른 고객들의 행동 참고
* 일반적으로는 사용자 기반보다 아이템 기반 협업 필터링이 정확도가 높다.  
    * 비슷한 병원을 선호했다고 사용자의 병원선택 기준이 비슷하다고 판단하기 어렵거나 매우 유명한 병원의 경우 선호하는 병원과 관계없이 선택하는 경우가 많고 평점을 매기지 않는 경우가 많기 때문이다.

### 병원과 평점 데이터를 병원 id기준으로 병합

In [55]:
rating_hospital = pd.merge(meta1, df, on='id')
rating_hospital.head(2)

,id,name,location,phonenumber,category,province,xpos,ypos,user_id,rating
0,1,행복한요양병원,경기도 안산시 단원구 고잔동 704-2 201호,NaN,NaN,경기,126.827683,37.313547,277,4
1,1,행복한요양병원,경기도 안산시 단원구 고잔동 704-2 201호,NaN,NaN,경기,126.827683,37.313547,295,1

### rating데이터를 각 사용자의 평점을 보기 쉽게 pivot_table로 변경

In [56]:
ratings_matrix = rating_hospital.pivot_table('rating', index='user_id', columns='name')
ratings_matrix.fillna(0, inplace=True)
ratings_matrix.head(2)

name,(의) 예림의료재단 청록요양병원,(의)밀성학원의료재단 성모요양병원,(의)성덕의료재단 간절곶자연요양병원,(의)수의료재단 서청솔요양병원,(의)영님의료재단 개금중앙요양병원,(의)피터의료재단새소망요양병원,(의)현당의료재단 늘봄요양병원,(의)환명의료재단 경상남도립김해노인전문병원,(재)대성재단 대성제일요양병원,(학교법인 경암학원)봉정요양병원,...,흥덕우리요양병원,흥해경희요양병원,희망요양병원,희망찬요양병원,희연요양병원,희윤요양병원,힐락암요양병원,힐링요양병원,힐링웰요양병원,힐링탑요양병원
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 유사도 측정
유사도 측정 위해 행렬 transpose(행, 열 전환)

In [57]:
ratings_matrix_T = ratings_matrix.transpose()
ratings_matrix_T.head(2)

user_id,1,2,3,4,5,6,7,8,9,10,...,591,592,593,594,595,596,597,598,599,600
name,,,,,,,,,,,,,,,,,,,,,
(의) 예림의료재단 청록요양병원,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(의)밀성학원의료재단 성모요양병원,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 코사인 유사도 측정

!pip install -U scikit-learn

In [58]:
from sklearn.metrics.pairwise import cosine_similarity

item_sim = cosine_similarity(ratings_matrix_T, ratings_matrix_T)
item_sim_df = pd.DataFrame(data=item_sim, index=ratings_matrix.columns, columns=ratings_matrix.columns)

print(item_sim_df.shape)
item_sim_df.head(2)

(1348, 1348)

name,(의) 예림의료재단 청록요양병원,(의)밀성학원의료재단 성모요양병원,(의)성덕의료재단 간절곶자연요양병원,(의)수의료재단 서청솔요양병원,(의)영님의료재단 개금중앙요양병원,(의)피터의료재단새소망요양병원,(의)현당의료재단 늘봄요양병원,(의)환명의료재단 경상남도립김해노인전문병원,(재)대성재단 대성제일요양병원,(학교법인 경암학원)봉정요양병원,...,흥덕우리요양병원,흥해경희요양병원,희망요양병원,희망찬요양병원,희연요양병원,희윤요양병원,힐락암요양병원,힐링요양병원,힐링웰요양병원,힐링탑요양병원
name,,,,,,,,,,,,,,,,,,,,,
(의) 예림의료재단 청록요양병원,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.218687,0.0,0.0,0.0,0.0,0.0,0.240981,0.0,0.0
(의)밀성학원의료재단 성모요양병원,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

### 추천 병원 dataframe반환 함수
해당병원과 평점이 비슷한 병원 추천

In [59]:
def find_sim_hospital_item(df, hospital_name, top_n=10):
    name_hospital_sim = df[[hospital_name]].drop(hospital_name, axis=0) #입력한 병원을 drop

    return name_hospital_sim.sort_values(hospital_name, ascending=False)[:top_n]

In [62]:
find_sim_hospital_item(item_sim_df, '새빛요양병원')

name                  새빛요양병원
name
도화요양병원              0.916698
의료법인 참사랑재단 참사랑요양병원  0.606043
담우요양병원              0.492515
동원요양병원              0.485071
연세엘림요양병원            0.327449
효인재활요양병원            0.250490
거제요양병원              0.225554
힐링웰요양병원             0.218299
한솔요양병원              0.166378
의료법인 자운의료재단 강남요양병원  0.128499